### PR TITLE
Fix`NotificationButton` issues

### LINKED ISSUE #348: Fix NotificationButton issues
- [ ]  align hover container properly with the bell icon;
- [ ] redirect or click actions should close the hovered area;
- [ ] resolve issue: _when you hover over account name on notifications, another small hover with account info should be displayed, but it's hiding behind the main container._

### PR DESCRIPTION
**Pull request by shelegdmitriy**
Closes #348

### CODE REVIEW

File: src/NearOrg/Notifications/NotificationButton.jsx [hunk 1]
```diff
@@ -9,6 +9,7 @@ const handleTurnOn = props?.handleTurnOn;
 const handleOnCancel = props?.handleOnCancel;
 const getNotificationLocalStorage = props?.getNotificationLocalStorage;
 const handleOnCancelBanner = props?.handleOnCancelBanner;
+const mobileView = props?.mobileView;
```
Comment (shelegdmitriy) [inline src/NearOrg/Notifications/NotificationButton.jsx:12]: We'll need this prop to use in `src/components/navigation/mobile/MobileNavigation.tsx` to prevent hover effect on mobile

**Review by charleslavon — APPROVED** [review]

**Review by marcinbodnar — APPROVED** [review]
Works well

**Comment by marcinbodnar** [comment]
@shelegdmitriy One small thing I noticed. When you quickly hover off and hover on the notifications list, the hover element blinks and eventually closes. I think it's missing a breakpoint, when the user hovers over the container while the animation of closing starts, this animation needs to break and start the animation to show it again.

https://github.com/near/near-discovery-components/assets/36210360/c2248d7c-4bb4-48ed-90d8-53c9a0c1cd0a

**Comment by charleslavon** [comment]
thanks for the video @marcinbodnar I used the action menu on your comment to quickly create [this issue](https://github.com/near/near-discovery-components/issues/350)

**Comment by marcinbodnar** [comment]
no problem :)
