### PR TITLE
Remove non-callable function

### LINKED ISSUE #335: Not a function call expression
**Describe the bug**
From yesterday it is not possible to open any component details.

**To Reproduce**
1. Go to any component e.g. https://test.near.org/discom.testnet/widget/ComponentDetailsPage?src=discom.testnet/widget/CommentButton
2. The screen will load with an error without component details

**Expected behavior**
The page should show component details. (code, preview)

**Screenshots**
Screenshot 2023-09-20 at 14 00 11

**Desktop (please complete the following information):**
 - OS: Mac
 - Browser Chrome
 - Version 116.0.5845.187

**Additional context**
The issue is reported by multiple people.

### PR DESCRIPTION
**Pull request by shelegdmitriy**
Closes #335

### CODE REVIEW

File: src/TosCheck.jsx [hunk 1]
```diff
@@ -145,7 +145,7 @@ const showTos =
   (!agreementsForUser.length ||
     agreementsForUser[agreementsForUser.length - 1].value < latestTosVersion);
 
-if (agreementsForUser) {
+if (agreementsForUser && recordToC) {
```
Comment (shelegdmitriy) [inline src/TosCheck.jsx:148]: We'll still need `recordToC` method. If you don't like this solution I'll remove it totally from here @charleslavon

**Review by charleslavon — APPROVED** [review]
